// SIGN IN ACTION TYPES

export const SIGNIN_REQUEST = Symbol('SIGNIN_REQUEST')

export const SIGNIN_SUCCESS = Symbol('SIGNIN_SUCCESS')

export const SIGNIN_FAILURE = Symbol('SIGNIN_FAILURE')
// APP STATE ACTION TYPES

export const TOGGLE_LOADING = Symbol('TOGGLE_LOADING')

export const TOGGLE_AUTH = Symbol('TOGGLE_AUTH')

export const AUTHENTICATE_USER = Symbol('AUTHENTICATE_USER')
